# pre-commit == 3.6.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: a11d9314b22d8f8c7556443875b731ef05965464
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-added-large-files
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.0.1
    hooks:
      - id: forbid-crlf
        files: \.md$
      - id: remove-crlf
        files: \.md$
      - id: forbid-tabs
        files: \.md$
      - id: remove-tabs
        files: \.md$
  - repo: local
    hooks:
      - id: run-erniebot-checks
        name: Run erniebot checks
        language: system
        entry: python scripts/run_erniebot_checks.py
        files: ^erniebot/
        pass_filenames: false
        stages: [pre-commit]
      - id: run-erniebot-agent-checks
        name: Run erniebot-agent checks
        language: system
        entry: python scripts/run_erniebot_agent_checks.py
        files: ^erniebot-agent/
        pass_filenames: false
        stages: [pre-commit]
