name: AgentUnitTest

on:
  push:
    paths:
      - .github/workflows/agent_*.yaml
      - erniebot-agent/**
  pull_request:
    paths:
      - .github/workflows/agent_*.yaml
      - erniebot-agent/**

jobs:
  AgentUnitTest:
    name: Agent Unit Test
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pip # Caching pip dependencies
          cache-dependency-path: |
            erniebot-agent/setup.cfg
            erniebot-agent/tests/requirements.txt
      - name: Install erniebot-agent and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e erniebot-agent[all]
          python -m pip install -r erniebot-agent/tests/requirements.txt
      - name: Run the commands
        run: cd erniebot-agent && python -m pytest tests/unit_tests
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
