name: Client CI

on:
  push:
    paths:
      - .github/workflows/client_*.yaml
      - erniebot/**
  pull_request:
    paths:
      - .github/workflows/client_*.yaml
      - erniebot/**

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: erniebot
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pip # Caching pip dependencies
          cache-dependency-path: &dep_file_paths |
            setup.cfg
            *-requirements.txt
      - name: Install erniebot and dependencies
        run: |
          python -m pip install -r dev-requirements.txt
          python -m pip install --upgrade pip
          python -m pip install .
      - name: Show make version
        run: make --version
      - name: Perform format checks on Python code
        run: make format-check
      - name: Lint Python code
        run: make lint
      - name: Perform type checks on Python code
        run: make type-check
